### ISSUE TITLE
Icons suggestions

### ISSUE THREAD

**Issue by Yagi-404** [Comdec35000/Simple-Icons#1]
### I have here some icons suggestions :

- .bat / .cmd (Batch)
- .sh (Shell)
- .md (MarkDown)
- .ps1 (PowerShell Script)
- .fs / .fsx / .fsi / .fsscript (F#)
- .exe

It should be great with this thanks !

**Comment by Comdec35000** [comment]
Hey
Thanks for your suggestion, i'll work on it !
This suggestion is accepted

**Comment by Comdec35000** [comment]
Suggestion added in version 0.1.0 Beta
You can downlaod it here : [Download](_apis/public/gallery/publishers/Comdec/vsextensions/simple-icons/0.1.0/vspackage)
Thank you again for the suggestion !
