### ISSUE TITLE
[Icon Suggestion] cmake, ninja (other build systems)

### ISSUE THREAD

**Issue by jkellers** [Comdec35000/Simple-Icons#2]
First of all, your icon theme is really awesome!

I would love to see an icon for cmake and ninja (maybe also other build systems, make, meson, ..). For cmake there is a official icon, for ninja I would suggest using a ninja shuriken or a small ninja.

Thanks!

**Comment by Comdec35000** [comment]
Thank you for the suggestion !

I’ll work on it soon (currently working on folder icons and other personal and irl project)
This suggestion is accepted !

**Comment by Comdec35000** [comment]
Suggestion added in version 0.1.0 Beta
You can downlaod it here : [Download](_apis/public/gallery/publishers/Comdec/vsextensions/simple-icons/0.1.0/vspackage)
Thank you again for the suggestion !
