### ISSUE TITLE
Question (No issues)

### ISSUE THREAD

**Issue by Samyak-Bumb** [Comdec35000/Simple-Icons#3]
Can you please make a **YouTube Video**? To know how did you made the extension 🙂😀.

**Comment by Samyak-Bumb** [comment]
.

**Comment by Comdec35000** [comment]
I don't think I will be making this kind of videos soon. Microsoft has a documentation for creating icons theme extensions, and there's a bunch of open source themes (including this one) to be used as exemples (please just don't use the icons of this theme without permission).

I'll maybe make a documentation/tutorial to explain how to, but it's not the first thing I have to do.
